version = 0.1

[default.deploy.parameters]
stack_name = "graph-ingest-chunk"
resolve_s3 = true
s3_prefix = "graph-ingest-chunk"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "InputBucketName=\"my-docling-input-data-2025\" OutputBucketName=\"my-docling-output-artifacts-2025\""
image_repositories = ["DoclingIngestFunction=757905896558.dkr.ecr.us-east-1.amazonaws.com/graphingestchunk4f6a4dbd/doclingingestfunction798cb798repo"]

[default.global.parameters]
region = "us-east-1"
